theme: jekyll-theme-midnight
title: ProtoMars's Website
description: The website I use for well, anything really.
nav:
  - title: Home
    url: ashprograms.github.io
  - title: Portfolio
    url: ashprograms.github.io/portfolio
  - title: Error Codes
    url: ashprograms.github.io/error-codes
